<?php
use Correction\TP6\Block\Customer\Addresses;

/** @var $block Addresses */
$addresses = $block->getAddresses();
?>
<ul>
<?php foreach ($addresses as $address) : ?>
    <li>
        <span><?php echo $address->getStreet(); ?></span>
        <span><?php echo $address->getCity(); ?></span>
        <span><?php echo $address->getZipCode(); ?></span>
        <span><?php echo $address->getCountry(); ?></span>
    </li>
<?php endforeach; ?>
</ul>